// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpvdzmdtevuyywnbadip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwdmR6bWR0ZXZ1eXl3bmJhZGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NzQ1NjgsImV4cCI6MjA1MTE1MDU2OH0.1ZVKYyPKbmin-_wIRp0jRr7nipGCXLXi_kOlaBxbnz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);